### ISSUE TITLE
How to deal with the data alignment between annotation and predictions

### ISSUE THREAD

**Issue by haopo2005** [ppengtang/dpl#1]
Hi,
I'm new of caffe. And I think data annotation is very common among all the detection training applications.
I'd like to know how to deal with the data alignment between annotation and predictions during forward computation in the loss function such as  smoothL1LossLayer function?
Concretely, suppose there are n*n  output cells and each cell can predict m bboxs from pervious conv layer, then  if there are p annotations per image.
How to make the annotataion dimensions map the predictions?

**Comment by ppengtang** [comment]
Maybe you can read the Fast RCNN paper and its code [https://github.com/rbgirshick/fast-rcnn](https://github.com/rbgirshick/fast-rcnn). This can help you to understand better.
